### ISSUE TITLE
Simulator Code 

### ISSUE THREAD

**Issue by Ray1580** [ruiqini/P-NTFields#2]
Hi @ruiqini Thanks for your excellent work about robot arm motion planning.
And i noticed that your got a sim.gif in your fig part, so i just wondering is there any code for your simulator.
Thanks!!

**Comment by ruiqini** [comment]
Thanks for your question. By simulation, we mean it is a virtual environment and we don't use a simulator. We only visualize the kinematic path (waypoints) and validate if it is collision-free. For real setup, we directly send these waypoints to the UR5 controller and it works well.

**Comment by Ray1580** [comment]
Sorry for my late reply and Thanks for your fast and kind respond! And i got last question about how do you select waypoints from the code. For me, after training the models and  tested the model with arm_plan, it poped out the kinematic path graph, and i have no ideas about how to select waypoints through kinematic graph.
Thanks!

**Comment by ruiqini** [comment]
I think the output in arm_plan is a list of waypoints with shape n*6 (called `xyz`). What do you mean by "kinematic path graph"?

**Comment by Ray1580** [comment]
Thanks, i found waypoints in arm_plan and what i mean kinematic path graph is picture down below
![Screenshot from 2023-11-16 14-28-45](https://github.com/ruiqini/P-NTFields/assets/45763036/13f5a753-7c0a-463a-9ff4-a6a0214dc5e0)

**Comment by ruiqini** [comment]
OK
